version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: kara_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: kara_app
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "3000:3000"
    command: >
      bash -lc "
      uvicorn app.main:app --host 0.0.0.0 --port 8000 &
      dagster dev -h 0.0.0.0 -p 3000
      "

volumes:
  pgdata:
