version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned messages from Telegram raw source."
    columns:
      - name: raw_id
        tests: [not_null, unique]
      - name: channel_name
        tests: [not_null]
      - name: message_id
        tests: [not_null]
      - name: posted_at
        tests: [not_null]
